const  breakingBad = [
    {
        "atomic_number": 1,
        "symbol": "H",
        "name": "Hydrogen",
        "atomic_mass": 1.008,
        "category": "diatomic nonmetal",
        "appearance": "colorless gas",
        "phase": "gas",
        "discovered_by": "Henry Cavendish",
        "year_discovered": 1766
    },
    {
        "atomic_number": 2,
        "symbol": "He",
        "name": "Helium",
        "atomic_mass": 4.002602,
        "category": "noble gas",
        "appearance": "colorless gas, exhibiting a red-orange glow when placed in a high-voltage electric field",
        "phase": "gas",
        "discovered_by": "Pierre Janssen",
        "year_discovered": 1868
    },
    {
        "atomic_number": 3,
        "symbol": "Li",
        "name": "Lithium",
        "atomic_mass": 6.94,
        "category": "alkali metal",
        "appearance": "silvery-white",
        "phase": "solid",
        "discovered_by": "Johan August Arfwedson",
        "year_discovered": 1817
    },
    {
        "atomic_number": 4,
        "symbol": "Be",
        "name": "Beryllium",
        "atomic_mass": 9.0121831,
        "category": "alkaline earth metal",
        "appearance": "white-gray metallic",
        "phase": "solid",
        "discovered_by": "Louis Nicolas Vauquelin",
        "year_discovered": 1798
    },
    {
        "atomic_number": 5,
        "symbol": "B",
        "name": "Boron",
        "atomic_mass": 10.81,
        "category": "metalloid",
        "appearance": "black-brown",
        "phase": "solid",
        "discovered_by": "Joseph Louis Gay-Lussac",
        "year_discovered": 1808
    },
    {
        "atomic_number": 6,
        "symbol": "C",
        "name": "Carbon",
        "atomic_mass": 12.011,
        "category": "polyatomic nonmetal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Ancient Egypt",
        "year_discovered": -3750
    },
    {
        "atomic_number": 7,
        "symbol": "N",
        "name": "Nitrogen",
        "atomic_mass": 14.007,
        "category": "diatomic nonmetal",
        "appearance": "colorless gas, liquid or solid",
        "phase": "gas",
        "discovered_by": "Daniel Rutherford",
        "year_discovered": 1772
    },
    {
        "atomic_number": 8,
        "symbol": "O",
        "name": "Oxygen",
        "atomic_mass": 15.999,
        "category": "diatomic nonmetal",
        "appearance": "colorless gas, liquid and solid samples",
        "phase": "gas",
        "discovered_by": "Carl Wilhelm Scheele",
        "year_discovered": 1774
    },
    {
        "atomic_number": 9,
        "symbol": "F",
        "name": "Fluorine",
        "atomic_mass": 18.9984031636,
        "category": "diatomic nonmetal",
        "appearance": null,
        "phase": "gas",
        "discovered_by": "André-Marie Ampère",
        "year_discovered": 1670
    },
    {
        "atomic_number": 10,
        "symbol": "Ne",
        "name": "Neon",
        "atomic_mass": 20.17976,
        "category": "noble gas",
        "appearance": "colorless gas exhibiting an orange-red glow when placed in a high voltage electric field",
        "phase": "gas",
        "discovered_by": "Morris Travers",
        "year_discovered": 1898
    },
    {
        "atomic_number": 11,
        "symbol": "Na",
        "name": "Sodium",
        "atomic_mass": 22.989769282,
        "category": "alkali metal",
        "appearance": "silvery white metallic",
        "phase": "solid",
        "discovered_by": "Humphry Davy",
        "year_discovered": 1807
    },
    {
        "atomic_number": 12,
        "symbol": "Mg",
        "name": "Magnesium",
        "atomic_mass": 24.305,
        "category": "alkaline earth metal",
        "appearance": "shiny grey solid",
        "phase": "solid",
        "discovered_by": "Joseph Black",
        "year_discovered": 1755
    },
    {
        "atomic_number": 13,
        "symbol": "Al",
        "name": "Aluminium",
        "atomic_mass": 26.98153857,
        "category": "post-transition metal",
        "appearance": "silvery gray metallic",
        "phase": "solid",
        "discovered_by": "Hans Christian Ørsted",
        "year_discovered": 1825
    },
    {
        "atomic_number": 14,
        "symbol": "Si",
        "name": "Silicon",
        "atomic_mass": 28.085,
        "category": "metalloid",
        "appearance": "crystalline, reflective with bluish-tinged faces",
        "phase": "solid",
        "discovered_by": "Jöns Jacob Berzelius",
        "year_discovered": 1824
    },
    {
        "atomic_number": 15,
        "symbol": "P",
        "name": "Phosphorus",
        "atomic_mass": 30.9737619985,
        "category": "polyatomic nonmetal",
        "appearance": "colorless, waxy white, yellow, scarlet, red, violet, black",
        "phase": "solid",
        "discovered_by": "Hennig Brand",
        "year_discovered": 1669
    },
    {
        "atomic_number": 16,
        "symbol": "S",
        "name": "Sulfur",
        "atomic_mass": 32.06,
        "category": "polyatomic nonmetal",
        "appearance": "lemon yellow sintered microcrystals",
        "phase": "solid",
        "discovered_by": "Ancient china",
        "year_discovered": null
    },
    {
        "atomic_number": 17,
        "symbol": "Cl",
        "name": "Chlorine",
        "atomic_mass": 35.45,
        "category": "diatomic nonmetal",
        "appearance": "pale yellow-green gas",
        "phase": "gas",
        "discovered_by": "Carl Wilhelm Scheele",
        "year_discovered": 1774
    },
    {
        "atomic_number": 18,
        "symbol": "Ar",
        "name": "Argon",
        "atomic_mass": 39.9481,
        "category": "noble gas",
        "appearance": "colorless gas exhibiting a lilac/violet glow when placed in a high voltage electric field",
        "phase": "gas",
        "discovered_by": "Lord Rayleigh",
        "year_discovered": 1894
    },
    {
        "atomic_number": 19,
        "symbol": "K",
        "name": "Potassium",
        "atomic_mass": 39.09831,
        "category": "alkali metal",
        "appearance": "silvery gray",
        "phase": "solid",
        "discovered_by": "Humphry Davy",
        "year_discovered": 1807
    },
    {
        "atomic_number": 20,
        "symbol": "Ca",
        "name": "Calcium",
        "atomic_mass": 40.0784,
        "category": "alkaline earth metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Humphry Davy",
        "year_discovered": 1808
    },
    {
        "atomic_number": 21,
        "symbol": "Sc",
        "name": "Scandium",
        "atomic_mass": 44.9559085,
        "category": "transition metal",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Lars Fredrik Nilson",
        "year_discovered": 1879
    },
    {
        "atomic_number": 22,
        "symbol": "Ti",
        "name": "Titanium",
        "atomic_mass": 47.8671,
        "category": "transition metal",
        "appearance": "silvery grey-white metallic",
        "phase": "solid",
        "discovered_by": "William Gregor",
        "year_discovered": 1791
    },
    {
        "atomic_number": 23,
        "symbol": "V",
        "name": "Vanadium",
        "atomic_mass": 50.94151,
        "category": "transition metal",
        "appearance": "blue-silver-grey metal",
        "phase": "solid",
        "discovered_by": "Andrés Manuel del Río",
        "year_discovered": 1801
    },
    {
        "atomic_number": 24,
        "symbol": "Cr",
        "name": "Chromium",
        "atomic_mass": 51.99616,
        "category": "transition metal",
        "appearance": "silvery metallic",
        "phase": "solid",
        "discovered_by": "Louis Nicolas Vauquelin",
        "year_discovered": "Ancient"
    },
    {
        "atomic_number": 25,
        "symbol": "Mn",
        "name": "Manganese",
        "atomic_mass": 54.9380443,
        "category": "transition metal",
        "appearance": "silvery metallic",
        "phase": "solid",
        "discovered_by": "Torbern Olof Bergman",
        "year_discovered": 1774
    },
    {
        "atomic_number": 26,
        "symbol": "Fe",
        "name": "Iron",
        "atomic_mass": 55.8452,
        "category": "transition metal",
        "appearance": "lustrous metallic with a grayish tinge",
        "phase": "solid",
        "discovered_by": "Ancient Egypt",
        "year_discovered": null
    },
    {
        "atomic_number": 27,
        "symbol": "Co",
        "name": "Cobalt",
        "atomic_mass": 58.9331944,
        "category": "transition metal",
        "appearance": "hard lustrous gray metal",
        "phase": "solid",
        "discovered_by": "Georg Brandt",
        "year_discovered": "Ancient"
    },
    {
        "atomic_number": 28,
        "symbol": "Ni",
        "name": "Nickel",
        "atomic_mass": 58.69344,
        "category": "transition metal",
        "appearance": "lustrous, metallic, and silver with a gold tinge",
        "phase": "solid",
        "discovered_by": "Axel Fredrik Cronstedt",
        "year_discovered": 1751
    },
    {
        "atomic_number": 29,
        "symbol": "Cu",
        "name": "Copper",
        "atomic_mass": 63.5463,
        "category": "transition metal",
        "appearance": "red-orange metallic luster when freshly cut, but it oxidizes to a dull brown color",
        "phase": "solid",
        "discovered_by": "Middle East",
        "year_discovered": "Ancient"
    },
    {
        "atomic_number": 30,
        "symbol": "Zn",
        "name": "Zinc",
        "atomic_mass": 65.382,
        "category": "transition metal",
        "appearance": "silver-gray",
        "phase": "solid",
        "discovered_by": "India",
        "year_discovered": 1735
    },
    {
        "atomic_number": 31,
        "symbol": "Ga",
        "name": "Gallium",
        "atomic_mass": 69.7231,
        "category": "post-transition metal",
        "appearance": "silver-white",
        "phase": "solid",
        "discovered_by": "Lecoq de Boisbaudran",
        "year_discovered": 1875
    },
    {
        "atomic_number": 32,
        "symbol": "Ge",
        "name": "Germanium",
        "atomic_mass": 72.6308,
        "category": "metalloid",
        "appearance": "grayish-white",
        "phase": "solid",
        "discovered_by": "Clemens Winkler",
        "year_discovered": 1886
    },
    {
        "atomic_number": 33,
        "symbol": "As",
        "name": "Arsenic",
        "atomic_mass": 74.9215956,
        "category": "metalloid",
        "appearance": "metallic grey",
        "phase": "solid",
        "discovered_by": "Bronze Age",
        "year_discovered": null
    },
    {
        "atomic_number": 34,
        "symbol": "Se",
        "name": "Selenium",
        "atomic_mass": 78.9718,
        "category": "polyatomic nonmetal",
        "appearance": "black, red, and gray (not pictured) allotropes",
        "phase": "solid",
        "discovered_by": "Jöns Jakob Berzelius",
        "year_discovered": 1817
    },
    {
        "atomic_number": 35,
        "symbol": "Br",
        "name": "Bromine",
        "atomic_mass": 79.904,
        "category": "diatomic nonmetal",
        "appearance": "reddish-brown",
        "phase": "liquid",
        "discovered_by": "Antoine Jérôme Balard",
        "year_discovered": 1826
    },
    {
        "atomic_number": 36,
        "symbol": "Kr",
        "name": "Krypton",
        "atomic_mass": 83.7982,
        "category": "noble gas",
        "appearance": "colorless gas, exhibiting a whitish glow in a high electric field",
        "phase": "gas",
        "discovered_by": "William Ramsay",
        "year_discovered": 1898
    },
    {
        "atomic_number": 37,
        "symbol": "Rb",
        "name": "Rubidium",
        "atomic_mass": 85.46783,
        "category": "alkali metal",
        "appearance": "grey white",
        "phase": "solid",
        "discovered_by": "Robert Bunsen",
        "year_discovered": 1861
    },
    {
        "atomic_number": 38,
        "symbol": "Sr",
        "name": "Strontium",
        "atomic_mass": 87.621,
        "category": "alkaline earth metal",
        "appearance": "silvery white metallic",
        "phase": "solid",
        "discovered_by": "William Cruickshank (chemist)",
        "year_discovered": 1790
    },
    {
        "atomic_number": 39,
        "symbol": "Y",
        "name": "Yttrium",
        "atomic_mass": 88.905842,
        "category": "transition metal",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Johan Gadolin",
        "year_discovered": 1794
    },
    {
        "atomic_number": 40,
        "symbol": "Zr",
        "name": "Zirconium",
        "atomic_mass": 91.2242,
        "category": "transition metal",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Martin Heinrich Klaproth",
        "year_discovered": 1789
    },
    {
        "atomic_number": 41,
        "symbol": "Nb",
        "name": "Niobium",
        "atomic_mass": 92.906372,
        "category": "transition metal",
        "appearance": "gray metallic, bluish when oxidized",
        "phase": "solid",
        "discovered_by": "Charles Hatchett",
        "year_discovered": 1801
    },
    {
        "atomic_number": 42,
        "symbol": "Mo",
        "name": "Molybdenum",
        "atomic_mass": 95.951,
        "category": "transition metal",
        "appearance": "gray metallic",
        "phase": "solid",
        "discovered_by": "Carl Wilhelm Scheele",
        "year_discovered": 1778
    },
    {
        "atomic_number": 43,
        "symbol": "Tc",
        "name": "Technetium",
        "atomic_mass": 98,
        "category": "transition metal",
        "appearance": "shiny gray metal",
        "phase": "solid",
        "discovered_by": "Emilio Segrè",
        "year_discovered": 1937
    },
    {
        "atomic_number": 44,
        "symbol": "Ru",
        "name": "Ruthenium",
        "atomic_mass": 101.072,
        "category": "transition metal",
        "appearance": "silvery white metallic",
        "phase": "solid",
        "discovered_by": "Karl Ernst Claus",
        "year_discovered": 1844
    },
    {
        "atomic_number": 45,
        "symbol": "Rh",
        "name": "Rhodium",
        "atomic_mass": 102.905502,
        "category": "transition metal",
        "appearance": "silvery white metallic",
        "phase": "solid",
        "discovered_by": "William Hyde Wollaston",
        "year_discovered": 1803
    },
    {
        "atomic_number": 46,
        "symbol": "Pd",
        "name": "Palladium",
        "atomic_mass": 106.421,
        "category": "transition metal",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "William Hyde Wollaston",
        "year_discovered": 1803
    },
    {
        "atomic_number": 47,
        "symbol": "Ag",
        "name": "Silver",
        "atomic_mass": 107.86822,
        "category": "transition metal",
        "appearance": "lustrous white metal",
        "phase": "solid",
        "discovered_by": "Ancient",
        "year_discovered": null
    },
    {
        "atomic_number": 48,
        "symbol": "Cd",
        "name": "Cadmium",
        "atomic_mass": 112.4144,
        "category": "transition metal",
        "appearance": "silvery bluish-gray metallic",
        "phase": "solid",
        "discovered_by": "Karl Samuel Leberecht Hermann",
        "year_discovered": 1817
    },
    {
        "atomic_number": 49,
        "symbol": "In",
        "name": "Indium",
        "atomic_mass": 114.8181,
        "category": "post-transition metal",
        "appearance": "silvery lustrous gray",
        "phase": "solid",
        "discovered_by": "Ferdinand Reich",
        "year_discovered": 1863
    },
    {
        "atomic_number": 50,
        "symbol": "Sn",
        "name": "Tin",
        "atomic_mass": 118.7107,
        "category": "post-transition metal",
        "appearance": "silvery-white (beta, β) or gray (alpha, α)",
        "phase": "solid",
        "discovered_by": "Ancient",
        "year_discovered": "Ancient"
    },
    {
        "atomic_number": 51,
        "symbol": "Sb",
        "name": "Antimony",
        "atomic_mass": 121.7601,
        "category": "metalloid",
        "appearance": "silvery lustrous gray",
        "phase": "solid",
        "discovered_by": "Ancient",
        "year_discovered": "Ancient"
    },
    {
        "atomic_number": 52,
        "symbol": "Te",
        "name": "Tellurium",
        "atomic_mass": 127.603,
        "category": "metalloid",
        "appearance": "silvery lustrous gray",
        "phase": "solid",
        "discovered_by": "Franz-Joseph Müller von Reichenstein",
        "year_discovered": 1782
    },
    {
        "atomic_number": 53,
        "symbol": "I",
        "name": "Iodine",
        "atomic_mass": 126.904473,
        "category": "diatomic nonmetal",
        "appearance": "lustrous metallic gray, violet as a gas",
        "phase": "solid",
        "discovered_by": "Bernard Courtois",
        "year_discovered": 1811
    },
    {
        "atomic_number": 54,
        "symbol": "Xe",
        "name": "Xenon",
        "atomic_mass": 131.2936,
        "category": "noble gas",
        "appearance": "colorless gas, exhibiting a blue glow when placed in a high voltage electric field",
        "phase": "gas",
        "discovered_by": "William Ramsay",
        "year_discovered": 1898
    },
    {
        "atomic_number": 55,
        "symbol": "Cs",
        "name": "Cesium",
        "atomic_mass": 132.905451966,
        "category": "alkali metal",
        "appearance": "pale gold",
        "phase": "solid",
        "discovered_by": "Robert Bunsen",
        "year_discovered": 1860
    },
    {
        "atomic_number": 56,
        "symbol": "Ba",
        "name": "Barium",
        "atomic_mass": 137.3277,
        "category": "alkaline earth metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Carl Wilhelm Scheele",
        "year_discovered": 1808
    },
    {
        "atomic_number": 57,
        "symbol": "La",
        "name": "Lanthanum",
        "atomic_mass": 138.905477,
        "category": "lanthanide",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Carl Gustaf Mosander",
        "year_discovered": 1839
    },
    {
        "atomic_number": 58,
        "symbol": "Ce",
        "name": "Cerium",
        "atomic_mass": 140.1161,
        "category": "lanthanide",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Martin Heinrich Klaproth",
        "year_discovered": 1803
    },
    {
        "atomic_number": 59,
        "symbol": "Pr",
        "name": "Praseodymium",
        "atomic_mass": 140.907662,
        "category": "lanthanide",
        "appearance": "grayish white",
        "phase": "solid",
        "discovered_by": "Carl Auer von Welsbach",
        "year_discovered": 1885
    },
    {
        "atomic_number": 60,
        "symbol": "Nd",
        "name": "Neodymium",
        "atomic_mass": 144.2423,
        "category": "lanthanide",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Carl Auer von Welsbach",
        "year_discovered": 1885
    },
    {
        "atomic_number": 61,
        "symbol": "Pm",
        "name": "Promethium",
        "atomic_mass": 145,
        "category": "lanthanide",
        "appearance": "metallic",
        "phase": "solid",
        "discovered_by": "Chien Shiung Wu",
        "year_discovered": 1945
    },
    {
        "atomic_number": 62,
        "symbol": "Sm",
        "name": "Samarium",
        "atomic_mass": 150.362,
        "category": "lanthanide",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Lecoq de Boisbaudran",
        "year_discovered": 1853
    },
    {
        "atomic_number": 63,
        "symbol": "Eu",
        "name": "Europium",
        "atomic_mass": 151.9641,
        "category": "lanthanide",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Eugène-Anatole Demarçay",
        "year_discovered": 1901
    },
    {
        "atomic_number": 64,
        "symbol": "Gd",
        "name": "Gadolinium",
        "atomic_mass": 157.253,
        "category": "lanthanide",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Jean Charles Galissard de Marignac",
        "year_discovered": 1880
    },
    {
        "atomic_number": 65,
        "symbol": "Tb",
        "name": "Terbium",
        "atomic_mass": 158.925352,
        "category": "lanthanide",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Carl Gustaf Mosander",
        "year_discovered": 1843
    },
    {
        "atomic_number": 66,
        "symbol": "Dy",
        "name": "Dysprosium",
        "atomic_mass": 162.5001,
        "category": "lanthanide",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Lecoq de Boisbaudran",
        "year_discovered": 1886
    },
    {
        "atomic_number": 67,
        "symbol": "Ho",
        "name": "Holmium",
        "atomic_mass": 164.930332,
        "category": "lanthanide",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Marc Delafontaine",
        "year_discovered": 1878
    },
    {
        "atomic_number": 68,
        "symbol": "Er",
        "name": "Erbium",
        "atomic_mass": 167.2593,
        "category": "lanthanide",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Carl Gustaf Mosander",
        "year_discovered": 1842
    },
    {
        "atomic_number": 69,
        "symbol": "Tm",
        "name": "Thulium",
        "atomic_mass": 168.934222,
        "category": "lanthanide",
        "appearance": "silvery gray",
        "phase": "solid",
        "discovered_by": "Per Teodor Cleve",
        "year_discovered": 1879
    },
    {
        "atomic_number": 70,
        "symbol": "Yb",
        "name": "Ytterbium",
        "atomic_mass": 173.0451,
        "category": "lanthanide",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Jean Charles Galissard de Marignac",
        "year_discovered": 1878
    },
    {
        "atomic_number": 71,
        "symbol": "Lu",
        "name": "Lutetium",
        "atomic_mass": 174.96681,
        "category": "lanthanide",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Carl Gustaf Mosander",
        "year_discovered": 1907
    },
    {
        "atomic_number": 72,
        "symbol": "Hf",
        "name": "Hafnium",
        "atomic_mass": 178.492,
        "category": "transition metal",
        "appearance": "steel gray",
        "phase": "solid",
        "discovered_by": "Dirk Coster",
        "year_discovered": 1923
    },
    {
        "atomic_number": 73,
        "symbol": "Ta",
        "name": "Tantalum",
        "atomic_mass": 180.947882,
        "category": "transition metal",
        "appearance": "gray blue",
        "phase": "solid",
        "discovered_by": "Anders Gustaf Ekeberg",
        "year_discovered": 1802
    },
    {
        "atomic_number": 74,
        "symbol": "W",
        "name": "Tungsten",
        "atomic_mass": 183.841,
        "category": "transition metal",
        "appearance": "grayish white, lustrous",
        "phase": "solid",
        "discovered_by": "Carl Wilhelm Scheele",
        "year_discovered": 1781
    },
    {
        "atomic_number": 75,
        "symbol": "Re",
        "name": "Rhenium",
        "atomic_mass": 186.2071,
        "category": "transition metal",
        "appearance": "silvery-grayish",
        "phase": "solid",
        "discovered_by": "Masataka Ogawa",
        "year_discovered": 1908
    },
    {
        "atomic_number": 76,
        "symbol": "Os",
        "name": "Osmium",
        "atomic_mass": 190.233,
        "category": "transition metal",
        "appearance": "silvery, blue cast",
        "phase": "solid",
        "discovered_by": "Smithson Tennant",
        "year_discovered": 1803
    },
    {
        "atomic_number": 77,
        "symbol": "Ir",
        "name": "Iridium",
        "atomic_mass": 192.2173,
        "category": "transition metal",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Smithson Tennant",
        "year_discovered": 1803
    },
    {
        "atomic_number": 78,
        "symbol": "Pt",
        "name": "Platinum",
        "atomic_mass": 195.0849,
        "category": "transition metal",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Antonio de Ulloa",
        "year_discovered": "Ancient"
    },
    {
        "atomic_number": 79,
        "symbol": "Au",
        "name": "Gold",
        "atomic_mass": 196.9665695,
        "category": "transition metal",
        "appearance": "metallic yellow",
        "phase": "solid",
        "discovered_by": "Middle East",
        "year_discovered": "Ancient"
    },
    {
        "atomic_number": 80,
        "symbol": "Hg",
        "name": "Mercury",
        "atomic_mass": 200.5923,
        "category": "transition metal",
        "appearance": "silvery",
        "phase": "liquid",
        "discovered_by": "Ancient China",
        "year_discovered": "Ancient"
    },
    {
        "atomic_number": 81,
        "symbol": "Tl",
        "name": "Thallium",
        "atomic_mass": 204.38,
        "category": "post-transition metal",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "William Crookes",
        "year_discovered": 1861
    },
    {
        "atomic_number": 82,
        "symbol": "Pb",
        "name": "Lead",
        "atomic_mass": 207.21,
        "category": "post-transition metal",
        "appearance": "metallic gray",
        "phase": "solid",
        "discovered_by": "Middle East",
        "year_discovered": "Ancient"
    },
    {
        "atomic_number": 83,
        "symbol": "Bi",
        "name": "Bismuth",
        "atomic_mass": 208.980401,
        "category": "post-transition metal",
        "appearance": "lustrous silver",
        "phase": "solid",
        "discovered_by": "Claude François Geoffroy",
        "year_discovered": "Ancient"
    },
    {
        "atomic_number": 84,
        "symbol": "Po",
        "name": "Polonium",
        "atomic_mass": 209,
        "category": "post-transition metal",
        "appearance": "silvery",
        "phase": "solid",
        "discovered_by": "Pierre Curie",
        "year_discovered": 1898
    },
    {
        "atomic_number": 85,
        "symbol": "At",
        "name": "Astatine",
        "atomic_mass": 210,
        "category": "halogen",
        "appearance": "unknown, probably metallic",
        "phase": "solid",
        "discovered_by": "Dale R. Corson",
        "year_discovered": 1940
    },
    {
        "atomic_number": 86,
        "symbol": "Rn",
        "name": "Radon",
        "atomic_mass": 222,
        "category": "noble gas",
        "appearance": "colorless gas, occasionally glows green or red in discharge tubes",
        "phase": "gas",
        "discovered_by": "Friedrich Ernst Dorn",
        "year_discovered": 1898
    },
    {
        "atomic_number": 87,
        "symbol": "Fr",
        "name": "Francium",
        "atomic_mass": 223,
        "category": "alkali metal",
        "appearance": "unknown, probably metallic",
        "phase": "solid",
        "discovered_by": "Marguerite Perey",
        "year_discovered": 1939
    },
    {
        "atomic_number": 88,
        "symbol": "Ra",
        "name": "Radium",
        "atomic_mass": 226,
        "category": "alkaline earth metal",
        "appearance": "silvery white metallic",
        "phase": "solid",
        "discovered_by": "Pierre Curie",
        "year_discovered": 1898
    },
    {
        "atomic_number": 89,
        "symbol": "Ac",
        "name": "Actinium",
        "atomic_mass": 227,
        "category": "actinide",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Friedrich Oskar Giesel",
        "year_discovered": 1899
    },
    {
        "atomic_number": 90,
        "symbol": "Th",
        "name": "Thorium",
        "atomic_mass": 232.03774,
        "category": "actinide",
        "appearance": "silvery, often with black tarnish",
        "phase": "solid",
        "discovered_by": "Jöns Jakob Berzelius",
        "year_discovered": 1828
    },
    {
        "atomic_number": 91,
        "symbol": "Pa",
        "name": "Protactinium",
        "atomic_mass": 231.035882,
        "category": "actinide",
        "appearance": "bright, silvery metallic luster",
        "phase": "solid",
        "discovered_by": "William Crookes",
        "year_discovered": 1913
    },
    {
        "atomic_number": 92,
        "symbol": "U",
        "name": "Uranium",
        "atomic_mass": 238.028913,
        "category": "actinide",
        "appearance": "silvery gray metallic",
        "phase": "solid",
        "discovered_by": "Martin Heinrich Klaproth",
        "year_discovered": 1789
    },
    {
        "atomic_number": 93,
        "symbol": "Np",
        "name": "Neptunium",
        "atomic_mass": 237,
        "category": "actinide",
        "appearance": "silvery metallic",
        "phase": "solid",
        "discovered_by": "Edwin McMillan",
        "year_discovered": 1940
    },
    {
        "atomic_number": 94,
        "symbol": "Pu",
        "name": "Plutonium",
        "atomic_mass": 244,
        "category": "actinide",
        "appearance": "silvery white, tarnishing to dark gray in air",
        "phase": "solid",
        "discovered_by": "Glenn T. Seaborg",
        "year_discovered": 1940
    },
    {
        "atomic_number": 95,
        "symbol": "Am",
        "name": "Americium",
        "atomic_mass": 243,
        "category": "actinide",
        "appearance": "silvery white",
        "phase": "solid",
        "discovered_by": "Glenn T. Seaborg",
        "year_discovered": 1944
    },
    {
        "atomic_number": 96,
        "symbol": "Cm",
        "name": "Curium",
        "atomic_mass": 247,
        "category": "actinide",
        "appearance": "silvery metallic, glows purple in the dark",
        "phase": "solid",
        "discovered_by": "Glenn T. Seaborg",
        "year_discovered": 1944
    },
    {
        "atomic_number": 97,
        "symbol": "Bk",
        "name": "Berkelium",
        "atomic_mass": 247,
        "category": "actinide",
        "appearance": "silvery",
        "phase": "solid",
        "discovered_by": "Lawrence Berkeley National Laboratory",
        "year_discovered": 1949
    },
    {
        "atomic_number": 98,
        "symbol": "Cf",
        "name": "Californium",
        "atomic_mass": 251,
        "category": "actinide",
        "appearance": "silvery",
        "phase": "solid",
        "discovered_by": "Lawrence Berkeley National Laboratory",
        "year_discovered": 1950
    },
    {
        "atomic_number": 99,
        "symbol": "Es",
        "name": "Einsteinium",
        "atomic_mass": 252,
        "category": "actinide",
        "appearance": "silver-colored",
        "phase": "solid",
        "discovered_by": "Lawrence Berkeley National Laboratory",
        "year_discovered": 1952
    },
    {
        "atomic_number": 100,
        "symbol": "Fm",
        "name": "Fermium",
        "atomic_mass": 257,
        "category": "actinide",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Lawrence Berkeley National Laboratory",
        "year_discovered": 1952
    },
    {
        "atomic_number": 101,
        "symbol": "Md",
        "name": "Mendelevium",
        "atomic_mass": 258,
        "category": "actinide",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Lawrence Berkeley National Laboratory",
        "year_discovered": 1955
    },
    {
        "atomic_number": 102,
        "symbol": "No",
        "name": "Nobelium",
        "atomic_mass": 259,
        "category": "actinide",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Joint Institute for Nuclear Research",
        "year_discovered": 1958
    },
    {
        "atomic_number": 103,
        "symbol": "Lr",
        "name": "Lawrencium",
        "atomic_mass": 266,
        "category": "transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Lawrence Berkeley National Laboratory",
        "year_discovered": 1961
    },
    {
        "atomic_number": 104,
        "symbol": "Rf",
        "name": "Rutherfordium",
        "atomic_mass": 267,
        "category": "transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Joint Institute for Nuclear Research",
        "year_discovered": 1964
    },
    {
        "atomic_number": 105,
        "symbol": "Db",
        "name": "Dubnium",
        "atomic_mass": 268,
        "category": "transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Joint Institute for Nuclear Research",
        "year_discovered": 1967
    },
    {
        "atomic_number": 106,
        "symbol": "Sg",
        "name": "Seaborgium",
        "atomic_mass": 269,
        "category": "transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Lawrence Berkeley National Laboratory",
        "year_discovered": 1974
    },
    {
        "atomic_number": 107,
        "symbol": "Bh",
        "name": "Bohrium",
        "atomic_mass": 270,
        "category": "transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Gesellschaft für Schwerionenforschung",
        "year_discovered": 1981
    },
    {
        "atomic_number": 108,
        "symbol": "Hs",
        "name": "Hassium",
        "atomic_mass": 269,
        "category": "transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Gesellschaft für Schwerionenforschung",
        "year_discovered": 1984
    },
    {
        "atomic_number": 109,
        "symbol": "Mt",
        "name": "Meitnerium",
        "atomic_mass": 278,
        "category": "transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Gesellschaft für Schwerionenforschung",
        "year_discovered": 1982
    },
    {
        "atomic_number": 110,
        "symbol": "Ds",
        "name": "Darmstadtium",
        "atomic_mass": 281,
        "category": "transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Gesellschaft für Schwerionenforschung",
        "year_discovered": 1994
    },
    {
        "atomic_number": 111,
        "symbol": "Rg",
        "name": "Roentgenium",
        "atomic_mass": 282,
        "category": "transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Gesellschaft für Schwerionenforschung",
        "year_discovered": 1994
    },
    {
        "atomic_number": 112,
        "symbol": "Cn",
        "name": "Copernicium",
        "atomic_mass": 285,
        "category": "transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Gesellschaft für Schwerionenforschung",
        "year_discovered": 1996
    },
    {
        "atomic_number": 113,
        "symbol": "Nh",
        "name": "Nihonium",
        "atomic_mass": 286,
        "category": "post-transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "RIKEN",
        "year_discovered": 2003
    },
    {
        "atomic_number": 114,
        "symbol": "Fl",
        "name": "Flerovium",
        "atomic_mass": 289,
        "category": "post-transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Joint Institute for Nuclear Research",
        "year_discovered": 1999
    },
    {
        "atomic_number": 115,
        "symbol": "Mc",
        "name": "Moscovium",
        "atomic_mass": 288,
        "category": "post-transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Joint Institute for Nuclear Research",
        "year_discovered": 2003
    },
    {
        "atomic_number": 116,
        "symbol": "Lv",
        "name": "Livermorium",
        "atomic_mass": 293,
        "category": "post-transition metal",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Joint Institute for Nuclear Research",
        "year_discovered": 2000
    },
    {
        "atomic_number": 117,
        "symbol": "Ts",
        "name": "Tennessine",
        "atomic_mass": 294,
        "category": "halogen",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Joint Institute for Nuclear Research",
        "year_discovered": 2010
    },
    {
        "atomic_number": 118,
        "symbol": "Og",
        "name": "Oganesson",
        "atomic_mass": 294,
        "category": "noble gas",
        "appearance": null,
        "phase": "solid",
        "discovered_by": "Joint Institute for Nuclear Research",
        "year_discovered": 2002
    }                                               
]      

export default breakingBad;
